version: '3.3'
services:
  app:
    build:
      dockerfile: ./docker/app/Dockerfile
      context: .
    volumes:
      - ./:/var/www/html
    networks:
      - app-network

  nginx:
    build:
      dockerfile: ./docker/nginx/Dockerfile
      context: .
    environment:
      SERVER_NAME: 'slim-app'
      PUBLIC_DIR: '/var/www/html/public'
      FPM_HOST: 'app:9000'
    volumes:
      - ./docker/nginx/app.conf.template:/etc/nginx/templates/default.conf.template
      - ./public:/var/www/html/public
    ports:
      - 8080:80
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
